services:

    app.task_updater:
        class: AppBundle\Installer\TaskUpdater
        tags: [{name: goat.updater}]

    app.twig.parsedown:
        class: AppBundle\Twig\Extension\ParsedownExtension
        tags: [{name: twig.extension}]

    app.twig.app:
        class: AppBundle\Twig\Extension\AppExtension
        arguments: ['@request_stack', '@router']
        tags: [{name: twig.extension}]

    app.task_mapper:
        class: AppBundle\Mapper\TaskMapper
        arguments: ['@goat.session']
        tags: [{name: goat.mapper, alias: "App:Task", class: "AppBundle\\Entity\\Task"}]

    app.note_mapper:
        class: AppBundle\Mapper\NoteMapper
        arguments: ['@goat.session']
        tags: [{name: goat.mapper, alias: "App:Note", class: "AppBundle\\Entity\\Note"}]

    app.alarm_mapper:
        class: AppBundle\Mapper\AlarmMapper
        arguments: ['@goat.session']
        tags: [{name: goat.mapper, alias: "App:Alarm", class: "AppBundle\\Entity\\Alarm"}]
