services:

    gestion.datetime_value_resolver:
        public: false
        class: GestionBundle\Controller\ArgumentResolver\DateTimeValueResolver
        tags: [{name: controller.argument_value_resolver, priority: 150}]

    gestion.gestion_updater:
        class: GestionBundle\Installer\GestionUpdater
        tags: [{name: goat.updater}]

    gestion.contract_mapper:
        class: GestionBundle\Mapper\ContractMapper
        arguments: ['@goat.session']
        tags: [{name: goat.mapper, alias: "Gestion:Contract", class: "GestionBundle\\Entity\\Contract"}]

    gestion.logement_mapper:
        class: GestionBundle\Mapper\LogementMapper
        arguments: ['@goat.session']
        tags: [{name: goat.mapper, alias: "Gestion:Logement", class: "GestionBundle\\Entity\\Logement"}]

    gestion.personne_mapper:
        class: GestionBundle\Mapper\PersonneMapper
        arguments: ['@goat.session']
        tags: [{name: goat.mapper, alias: "Gestion:Personne", class: "GestionBundle\\Entity\\Personne"}]

    gestion.quittance_mapper:
        class: GestionBundle\Mapper\QuittanceMapper
        arguments: ['@goat.session']
        tags: [{name: goat.mapper, alias: "Gestion:Quittance", class: "GestionBundle\\Entity\\Quittance"}]

    gestion.datasource.contract:
        public: true
        class: GestionBundle\Datasource\ContractDatasource
        arguments: ['@goat.session']
        tags: [{name: calista.datasource, id: gestion_contract}]

    gestion.datasource.quittance:
        public: true
        class: GestionBundle\Datasource\QuittanceDatasource
        arguments: ['@goat.session']
        tags: [{name: calista.datasource, id: gestion_quittance}]

    gestion.action_provider.contract:
        public: false
        class: GestionBundle\Action\ContractActionProvider
        tags: [{name: calista.action_provider}]
