monolog:
    handlers:
        main:
            # suspended, @see aavant gitlab #500
            # type: fingers_crossed
            # action_level: error
            # handler: nested
            # excluded_http_codes: [404, 405]
            # buffer_size: 150 # How many messages should be saved? Prevent memory leaks
            # nested:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            date_format: Y-m-d
            max_files: 30
            level: info
            formatter: monolog.formatter.line # Overriden using goat to display PID
            channels: ["!php"]
        php:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%-php.log"
            date_format: Y-m-d
            max_files: 30
            level: warning
            formatter: monolog.formatter.line # Overriden using goat to display PID
            channels: ["php"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
